importing useful libraries


In [ ]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

load iris datasets


In [ ]:
iris=datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
n_samples , n_features = X.shape
print(n_samples)
print(n_features)


150
4


split dataset into training and testing sets


In [ ]:
X_train , X_test ,y_train , y_test =train_test_split(X,y,test_size=0.2 ,random_state=42)

standardize data


In [ ]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test =sc.transform(X_test)

In [ ]:
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.int64)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.int64)

defining neural network

In [ ]:
class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

set hyperparameters

In [ ]:
input_size = 4
hidden_size = 8
output_size = 3
learning_rate = 0.01
num_epochs = 100

In [ ]:
model = SimpleNN(input_size, hidden_size, output_size)
criterion = nn.CrossEntropyLoss()
optimizer =torch. optim.SGD(model.parameters(), lr=learning_rate)

training loop


In [ ]:
for epoch in range(num_epochs):
  #forward pass
  y_predicted=model(X_train)
  loss= criterion(y_predicted,y_train)

  #backward pass
  loss.backward()

  #updates
  optimizer.step()

  #zero gradients
  optimizer.zero_grad()
  if (epoch + 1) % 10 == 0:
        print(f'epoch :{epoch+1}, Loss: {loss.item():.4f}')

epoch :10, Loss: 0.9760
epoch :20, Loss: 0.9392
epoch :30, Loss: 0.9043
epoch :40, Loss: 0.8711
epoch :50, Loss: 0.8395
epoch :60, Loss: 0.8093
epoch :70, Loss: 0.7809
epoch :80, Loss: 0.7542
epoch :90, Loss: 0.7290
epoch :100, Loss: 0.7053


accuracy of model

In [ ]:
with torch.no_grad():
    model.eval()
    y_predicted = model(X_test)
    _, y_predicted_cls = torch.max(y_predicted, 1)

acc = torch.sum(y_predicted_cls.eq(y_test)).item() / float(y_test.shape[0])
print(f'accuracy={acc*100:.4f}%')

accuracy=93.3333%
